void consequencias(){
  if(answer==2){
  if(per==0){
    if(res==0){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==1){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    if(res==2){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==3){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    }
    
    if(per==1){
      if(res==0){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    if(res==1){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    if(res==2){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==3){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    }
    
    if(per==2){
      if(res==0){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    if(res==1){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    if(res==2){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    if(res==3){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    }
    
    if(per==3){
      if(res==0){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    if(res==1){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    if(res==3){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==4){
      if(res==0){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==1){
      CA+=indice*(d3s/2);
      CS=true;
    }
    if(res==2){
      CA+=indice*(d3s/2);
      CS=true;
    }
    if(res==3){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==5){
    if(res==0){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    if(res==1){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA-=indice*((d3b/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CB=true;
      DS=true;
    }
    if(res==2){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==3){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    }
    
    if(per==6){
    if(res==0){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==1){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==2){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==3){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    }
    
    if(per==7){
    if(res==0){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==1){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    if(res==2){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==3){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    }
    
    if(per==8){
    if(res==0){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    if(res==1){
      force+=indice*d2s;
      BS=true;
    }
    if(res==2){
      force+=indice*d2s;
      BS=true;
    }
    if(res==3){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    }
    
    if(per==9){
    if(res==0){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==1){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==3){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    }
    
    if(per==10){
    if(res==0){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==3){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    }
    
    if(per==11){
    if(res==0){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==3){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CS=true;
      DS=true;
    }
    }
    
    if(per==12){
    if(res==0){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==1){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==2){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==3){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    }
    
    if(per==13){
    if(res==0){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    if(res==1){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    if(res==2){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==3){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    }
    
    if(per==14){
    if(res==0){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==1){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==2){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==3){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    }
    
    if(per==15){
    if(res==0){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    if(res==1){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==2){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==3){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    }
    
    if(per==16){
    if(res==0){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==1){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==2){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==3){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==17){
    if(res==0){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    if(res==1){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    if(res==2){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==3){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    }
    
    if(per==18){
    if(res==0){
      JK+=indice*(d1s*1.5);
      AS=true;
    }
    if(res==1){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==2){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==3){
      JK+=indice*(d1s*1.5);
      force-=indice*((d2b/4)*2);
      CA-=indice*((d3b/4)*2);
      droids-=indice*((d4b/4)*2);
      AS=true;
      BB=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==19){
    if(res==0){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==3){
      force-=indice*d2b;
      BB=true;
    }
    }
    
    if(per==20){
    if(res==0){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==1){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==2){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==3){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    }
    
    if(per==21){
    if(res==0){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==3){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    }
    
    if(per==22){
    if(res==0){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==1){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==2){
      JK+=indice*((d1s/2));
      force-=indice*((d2b)*1.5);
      CA+=indice*((d3s/2));
      droids+=indice*((d4s/2));
      AS=true;
      BB=true;
      CS=true;
      DS=true;
    }
    if(res==3){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    }
    
    if(per==23){
    if(res==0){
      JK-=indice*((d1b/2));
      force+=indice*((d2s)*1.5);
      CA-=indice*((d3b/2));
      droids-=indice*((d4b/2));
      AB=true;
      BS=true;
      CB=true;
      DB=true;
    }
    if(res==1){
      JK-=indice*((d1b/2));
      force+=indice*((d2s)*1.5);
      CA-=indice*((d3b/2));
      droids-=indice*((d4b/2));
      AB=true;
      BS=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==3){
      JK+=indice*((d1s/2));
      force-=indice*((d2b)*1.5);
      CA+=indice*((d3s/2));
      droids+=indice*((d4s/2));
      AS=true;
      BB=true;
      CS=true;
      DS=true;
    }
    }
    
    if(per==24){
    if(res==0){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==1){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==2){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==3){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    }
    
    if(per==25){
    if(res==0){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==1){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==3){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    }
    
    if(per==26){
    if(res==0){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    if(res==3){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    }
    
    if(per==27){
    if(res==0){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CS=true;
      DS=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==3){
      JK-=indice*((d1b/2));
      force+=indice*((d2s)*1.5);
      CA-=indice*((d3b/2));
      droids-=indice*((d4b/2));
      AB=true;
      BS=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==28){
    if(res==0){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CS=true;
      DS=true;
    }
    if(res==1){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==3){
      JK+=indice*((d1s/2));
      force-=indice*((d2b)*1.5);
      CA+=indice*((d3s/2));
      droids+=indice*((d4s/2));
      AS=true;
      BB=true;
      CS=true;
      DS=true;
    }
    }
  }
  
  
  
  

  
  
  if(answer==1){
  if(per==0){
    if(res==0){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==1){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    if(res==2){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    if(res==3){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    }
    
    if(per==1){
      if(res==0){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    if(res==1){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    if(res==2){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    if(res==3){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    }
    
    if(per==2){
      if(res==0){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    if(res==1){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    if(res==2){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    if(res==3){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    }
    
    if(per==3){
      if(res==0){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    if(res==1){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==2){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    if(res==3){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==4){
      if(res==0){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    if(res==1){
      CA-=indice*(d3s/2);
      CB=true;
    }
    if(res==2){
      CA-=indice*(d3s/2);
      CB=true;
    }
    if(res==3){
      CA+=indice*((d3s/3)*2);
      CS=true;
    }
    }
    
    if(per==5){
    if(res==0){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    if(res==1){
      CA+=indice*d3s;
      CS=true;
    }
    if(res==2){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    if(res==3){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    }
    
    if(per==6){
    if(res==0){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==3){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    }
    
    if(per==7){
    if(res==0){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==1){
      force+=indice*d2b;
      BS=true;
    }
    if(res==2){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==3){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    }
    
    if(per==8){
    if(res==0){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==1){
      force-=indice*d2b;
      BB=true;
    }
    if(res==2){
      force-=indice*d2b;
      BB=true;
    }
    if(res==3){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    }
    
    if(per==9){
    if(res==0){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==1){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==2){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==3){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    }
    
    if(per==10){
    if(res==0){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==1){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CS=true;
      DS=true;
    }
    if(res==2){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==3){
      CA+=indice*d3s;
      droids-=indice*d4b;
      CS=true;
      DB=true;
    }
    }
    
    if(per==11){
    if(res==0){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==3){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==12){
    if(res==0){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==1){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==2){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==3){
      force+=indice*d2s;
      CA-=indice*d3b;
      BS=true;
      CB=true;
    }
    }
    
    if(per==13){
    if(res==0){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    if(res==1){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    if(res==2){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==3){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    }
    
    if(per==14){
    if(res==0){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==1){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==3){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    }
    
    if(per==15){
    if(res==0){
      JK+=indice*d1s;
      CA-=indice*d3b;
      AS=true;
      CB=true;
    }
    if(res==1){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==2){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==3){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    }
    
    if(per==16){
    if(res==0){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==1){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==3){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==17){
    if(res==0){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    if(res==1){
      CA-=indice*d3b;
      droids+=indice*d4s;
      CB=true;
      DS=true;
    }
    if(res==2){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==3){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    }
    
    if(per==18){
    if(res==0){
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      BS=true;
      CS=true;
      DS=true;
    }
    if(res==1){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==2){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==3){
      JK-=indice*(d1b*1.5);
      force+=indice*((d2s/4)*2);
      CA+=indice*((d3s/4)*2);
      droids+=indice*((d4s/4)*2);
      AB=true;
      BS=true;
      CS=true;
      DS=true;
    }
    }
    
    if(per==19){
    if(res==0){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==1){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CS=true;
      DS=true;
    }
    if(res==2){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==3){
      force+=indice*d2s;
      BS=true;
    }
    }
    
    if(per==20){
    if(res==0){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==1){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==2){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==3){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    }
    
    if(per==21){
    if(res==0){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CS=true;
      DS=true;
    }
    if(res==1){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CS=true;
      DS=true;
    }
    if(res==2){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    if(res==3){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    }
    
    if(per==22){
    if(res==0){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==1){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==2){
      JK-=indice*((d1b/2));
      force+=indice*((d2s)*1.5);
      CA-=indice*((d3b/2));
      droids-=indice*((d4b/2));
      AB=true;
      BS=true;
      CB=true;
      DB=true;
    }
    if(res==3){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    }
    
    if(per==23){
    if(res==0){
      JK+=indice*((d1s/2));
      force-=indice*((d2b)*1.5);
      CA+=indice*((d3s/2));
      droids+=indice*((d4s/2));
      AS=true;
      BB=true;
      CS=true;
      DS=true;
    }
    if(res==1){
      JK+=indice*((d1s/2));
      force-=indice*((d2b)*1.5);
      CA+=indice*((d3s/2));
      droids+=indice*((d4s/2));
      AS=true;
      BB=true;
      CS=true;
      DS=true;
    }
    if(res==2){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==3){
      JK-=indice*((d1b/2));
      force+=indice*((d2s)*1.5);
      CA-=indice*((d3b/2));
      droids-=indice*((d4b/2));
      AB=true;
      BS=true;
      CB=true;
      DB=true;
    }
    }
    
    if(per==24){
    if(res==0){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==1){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    if(res==2){
      droids-=indice*d4b;
      force+=indice*d2s;
      BS=true;
      DB=true;
    }
    if(res==3){
      droids+=indice*d4s;
      force-=indice*d2b;
      DS=true;
      BB=true;
    }
    }
    
    if(per==25){
    if(res==0){
      JK-=indice*d1b;
      droids+=indice*d4s;
      AB=true;
      DS=true;
    }
    if(res==1){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==2){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==3){
      JK+=indice*d1s;
      droids-=indice*d4b;
      AS=true;
      DB=true;
    }
    }
    
    if(per==26){
    if(res==0){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      force-=indice*d2b;
      CA+=indice*d3s;
      BB=true;
      CS=true;
    }
    if(res==3){
      JK-=indice*d1b;
      CA+=indice*d3s;
      AB=true;
      CS=true;
    }
    }
    
    if(per==27){
    if(res==0){
      JK+=indice*((d1s/3)*2);
      force+=indice*((d2s/3)*2);
      CA+=indice*((d3s/3)*2);
      droids+=indice*((d4s/3)*2);
      AS=true;
      BS=true;
      CS=true;
      DS=true;
    }
    if(res==1){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==2){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==3){
      JK+=indice*((d1s/2));
      force-=indice*((d2b)*1.5);
      CA+=indice*((d3s/2));
      droids+=indice*((d4s/2));
      AS=true;
      BB=true;
      CS=true;
      DS=true;
    }
    }
    
    if(per==28){
    if(res==0){
      JK-=indice*((d1b/3)*2);
      force-=indice*((d2b/3)*2);
      CA-=indice*((d3b/3)*2);
      droids-=indice*((d4b/3)*2);
      AB=true;
      BB=true;
      CB=true;
      DB=true;
    }
    if(res==1){
      JK-=indice*d1b;
      force+=indice*d2s;
      AB=true;
      BS=true;
    }
    if(res==2){
      JK+=indice*d1s;
      force-=indice*d2b;
      AS=true;
      BB=true;
    }
    if(res==3){
      JK-=indice*((d1b/2));
      force+=indice*((d2s)*1.5);
      CA-=indice*((d3b/2));
      droids-=indice*((d4b/2));
      AB=true;
      BS=true;
      CB=true;
      DB=true;
    }
    }
  }
}
